{% set name = "opentelemetry-semantic-conventions" %}
{% set version = "0.62b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_semantic_conventions-{{ version }}.tar.gz
  sha256: cbfb3c8fc259575cf68a6e1b94083cc35adc4a6b06e8cf431efa0d62606c0097

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:

    - python >={{ python_min }}
    - opentelemetry-api ==1.41.0
    - typing-extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Semantic Conventions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
