{% set version = "0.62b1" %}

package:
  name: opentelemetry-semantic-conventions
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/opentelemetry-semantic-conventions/opentelemetry_semantic_conventions-{{ version }}.tar.gz
  sha256: c5cc6e04a7f8c7cdd30be2ed81499fa4e75bfbd52c9cb70d40af1f9cd3619802

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api ==1.41.1
    - typing-extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.semconv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/opentelemetry-semantic-conventions
  summary: OpenTelemetry Semantic Conventions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
